	subroutine phipol(j,mm,nodes,wei,nn,x,phi,wrk)
c
	implicit real *8 (a-h, o-z)
	real *8 nodes(mm),wei(mm),x(nn),wrk(2*mm),phi(nn)
	real *8 sum, one, two, half
c
c       The Cf2py lines allow f2py to generate a better Python interface.
c
c       Inputs:
Cf2py   integer check(0<=j && j<mm),depend(mm) :: j
Cf2py   intent(in) :: nodes
Cf2py   intent(in) :: wei
Cf2py   intent(in) :: x
c
c       Outputs:
Cf2py   intent(out) :: phi
c
c       Hidden args:
c       - scratch areas can be auto-generated by python
Cf2py   intent(hide,cache) :: wrk
c       - array sizes can be auto-determined
Cf2py   integer intent(hide),depend(x):: nn=len(x)
Cf2py   integer intent(hide),depend(nodes) :: mm = len(nodes)
