solved:
	rm -rf examples
	ln -s examples_solved examples
	rm -f workbook_solved.tex
	ln -s main.tex workbook_solved.tex
	pdflatex workbook_solved
	rm -f workbook_solved.tex

skeletons:
	rm -rf examples
	ln -s examples_skel examples
	rm -f workbook_skeletons.tex
	ln -s main.tex workbook_skeletons.tex
	pdflatex workbook_skeletons
	rm -f workbook_skeletons.tex

